setwd('C:/dev/code/Petra')

#analysis of the Delamere eDNA data

library(readxl)
library(vegan)
library(tidyr)
library(dplyr)
library(ggplot2)
library(VennDiagram)


#load the read data
allreads = read_xlsx('../../data/DelamereData.xlsx', sheet = 'SppSite')

#remove the transect data from this
#cols D0A:F3C, and delete col 99, the taxon detail column.
reads = allreads[,-c(40:75,135)] # just the Delamere pilot study data


################################################################################
#create a rarefied data frame - in case we want to do any diversity analysis!
#vegan assumes rows are samples and cols are species - site/species, need to transpose the data
reads_mat <- as.matrix(reads[, -1])   # remove Taxonomy column
rownames(reads_mat) <- reads$Taxonomy

# Transpose so rows = samples, cols = ASVs
reads_t <- t(reads_mat)
mode(reads_t) <- "numeric"
min_depth <- min(rowSums(reads_t))
rarefied <- rrarefy(reads_t, sample = min_depth)



#check spec acc curve against min read depth
#this outputs the rarefaction curves - i.e. the random resamples of the data 
#generated by randomly resampling each sample until min_depth per sample is reached
#and plotting the species richness 
rarecurve(reads_t, step = 1000, col = "blue", cex = 0.6, xlim = c(1,10000),
          xlab = "Reads per Sample", ylab = "Species Richness")
abline(v = 4218, col = "red", lty = 2, lwd = 2)

################################################################################
#Transpose back so that I can merge with Functional traits etc
# Transpose back to species × samples
rarefied_back <- t(rarefied)

# Convert to data frame for easier export
rarefied_df <- as.data.frame(rarefied_back)

# Add species column as first column
rarefied_df <- tibble::rownames_to_column(rarefied_df, var = "Species")

###############################################################################
#merge with fungal traits
traits = read.csv('../../data/FunctionalTraits.csv')

#some cells are empty rather than NA
traits$primary_lifestyle[traits$primary_lifestyle == ""] <- NA

 #split the taxonomy column so can merge by genus
rare.split <- rarefied_df %>%
   separate(Species, into = c("GENUS", "Species"), sep = "_")

fungi.merged = merge(rare.split, traits, by = 'GENUS', all.x = TRUE)

#tidy by deleting unrequired columns
fungi.merged = fungi.merged[,-c(136,137:141,143:157,156:159)]
                     
#explore the total community in all samples
lifestyle_counts <- fungi.merged %>%
  count(primary_lifestyle) %>%
  arrange(desc(n))

#this plot has everything in - i.e. you can see ~ 200 species with NA guild - 
#thats because those are the above guild level and/or spp with no guild found - 
#these are removed later
ggplot(lifestyle_counts, aes(x = reorder(primary_lifestyle, -n), y = n)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Number of Species per Primary Lifestyle",
       x = "Primary Lifestyle",
       y = "Number of Species") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#ALSO - NEED THIS DF FOR LATER - SO RUN THIS LINE!!!
checking_df <- fungi.merged %>%
  filter(is.na(primary_lifestyle)) %>%
  select(GENUS, Species, primary_lifestyle)


#save this for checking
checkingdf = write.csv(checking_df,'../../data/checking.csv')

################################################################################

# This section looks at the groups which are or arenot matched to guilds and tries
#to tidy them all up so that most can be grouped, and those matched at family
#and above are removed

#checking all the items with sp in species column. Some are genus level, 
#If a sequence is at same family level, the GENUS column say Theler[horaceae, say
#and Species column says sp.
#For emf at Genus level, the GENUS column says Thelephora, say, and the Species
#column say sp - so looking at the 'sp' in Species column does not isolate emf at
#above genus - needs a bit of work...

#to remove the >genus level matches, take the rows from checking_df 
#where Species column is sp, this has genus level AND above genus level
above_genus = checking_df %>% filter(Species == 'sp') #179

#remove rows from fungi.merged where GENUS&species match above_genus
#this is all fungi with a sp name AND a guild
spp_level_guild = fungi.merged %>%
  filter(Species != "sp", !is.na(primary_lifestyle)) #855

#this is all fungi with a sp name and no guild
species_level_noguild = fungi.merged %>%
  filter(Species != "sp", is.na(primary_lifestyle)) #11

#if there are rows where Species = sp and primary lifestyle NOT NA, then the 
#GENUS column must have been a proper genus name, so that there was a guild match
#other wise the genus column is not a genus name - its above, hence no match
#the are fungi at genus level with a guild
genus_level_guild = fungi.merged %>%
  filter(Species== "sp", !is.na(primary_lifestyle)) #284

#this is BOTH the above genus level fungi AND any that might have been at genus
#level - but the genus was not recognized by Functional Traits
genus_level_noguild = fungi.merged %>%
  filter(Species== "sp", is.na(primary_lifestyle)) #179 

#make df of genus_level_guild + spp_level_guild + species_level_noguild
allfungi = rbind.data.frame(spp_level_guild, species_level_noguild, genus_level_guild)

#tidy this up by removing all the weird cols from Functional Traits merge
allfungi = allfungi[,-c(100:105,107:122,123)]
#This is now the working df - the only items missing will be any at genus level,
#with sp for speices, but no guild match. They can only be found by inspection -
#there were 2

#################################################################################


library(stringr)

#add a column to merge all sapros to sapro rather than the separate types
allfungi$lifestyle <- ifelse(
  str_detect(allfungi$primary_lifestyle, "_"),
  str_extract(allfungi$primary_lifestyle, "(?<=_).*"),
  allfungi$primary_lifestyle
)


#explore the total community in all samples, when the lifestyles are merged
#for simplicity
lifestyle_counts <- allfungi %>%
  count(lifestyle) %>%
  arrange(desc(n))

ggplot(lifestyle_counts, aes(x = reorder(lifestyle, -n), y = n)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = n), vjust = -0.3) +  # <-- Add labels above bars
  labs(title = "Number of Species per Lifestyle",
       x = "Primary Lifestyle",
       y = "Number of Species") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
###############################################################################

###############################################################################
#NOW SOME ANALYSIS OF SAMPLING METHODS. WE CAN KEEP EVERYTHING TOGETHER AS A 
#SEPARATE ASV FOR THIS, AND KEEP ALL THE TAXA, NOT YET INTERESTED IN HOW MANY ECTOS 
#ETC...

# 1. SAC over 64 samples in 8m2
#extract the unpooled single samples, the roots and rhizo soil
#col 1 and 2 are genus,species
#run each data file one at a time to get increasing samples, just A, A and pooled, etc
# Define the three datasets
data1 <- allfungi[, c(3:7, 41:99)]               # A samples
data2 <- allfungi[, c(3:22, 41:99)]              # pooled + repeat aliquots
data3 <- allfungi[, -c(1:2, 100:124)]            # everything (roots and rhizo)

# Make presence/absence
data1[data1 > 0] <- 1
data2[data2 > 0] <- 1
data3[data3 > 0] <- 1

# Calculate SACs (transpose since vegan expects sites as rows)
sac1 <- specaccum(t(data1), method = "random")
sac2 <- specaccum(t(data2), method = "random")
sac3 <- specaccum(t(data3), method = "random")

# Convert each to a dataframe and label
df1 <- data.frame(Samples = sac1$sites, Richness = sac1$richness, SD = sac1$sd, Group = "A samples")
df2 <- data.frame(Samples = sac2$sites, Richness = sac2$richness, SD = sac2$sd, Group = "Pooled + repeats")
df3 <- data.frame(Samples = sac3$sites, Richness = sac3$richness, SD = sac3$sd, Group = "All samples")

# Combine all
sac_df <- bind_rows(df1, df2, df3)

# Plot with ggplot
ggplot(sac_df, aes(x = Samples, y = Richness, color = Group, fill = Group)) +
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = Richness - SD, ymax = Richness + SD), alpha = 0.2, colour = NA) +
  labs(
    x = "Number of Samples",
    y = "Cumulative Species Richness",
    title = "Species-Area Curve for Different Sample Sets"
  ) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    plot.title = element_text(face = "bold")
  )

################################################################################
#WHAT ABOUT JUST ECTOS
emf <- allfungi %>% filter(lifestyle == 'ectomycorrhizal')

# Subsets
emf_soil       <- emf[, c(3:7, 41:99)]
emf_root       <- emf[, c(32:40)]
emf_rhizo      <- emf[, c(23:31)]
emf_rhizo_root <- emf[, c(23:40)]

# Convert to presence/absence
emf_soil[emf_soil > 0]             <- 1
emf_root[emf_root > 0]             <- 1
emf_rhizo[emf_rhizo > 0]           <- 1
emf_rhizo_root[emf_rhizo_root > 0] <- 1

# Calculate species accumulation curves (transpose: sites as rows for vegan)
sac_soil       <- specaccum(t(emf_soil), method = "random")
sac_root       <- specaccum(t(emf_root), method = "random")
sac_rhizo      <- specaccum(t(emf_rhizo), method = "random")
sac_rhizo_root <- specaccum(t(emf_rhizo_root), method = "random")

# Function to tidy the SAC output
sac_to_df <- function(sac_obj, label) {
  data.frame(
    Sites    = sac_obj$sites,
    Richness = sac_obj$richness,
    SD       = sac_obj$sd,
    Group    = label
  )
}

# Combine into one dataframe
df_all <- rbind(
  sac_to_df(sac_soil,       "Soil"),
  sac_to_df(sac_root,       "Root"),
  sac_to_df(sac_rhizo,      "Rhizosphere"),
  sac_to_df(sac_rhizo_root, "Rhizo + Root")
)

# Plot
ggplot(df_all, aes(x = Sites, y = Richness, color = Group, fill = Group)) +
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = Richness - SD, ymax = Richness + SD), alpha = 0.2, linetype = 0) +
  theme_minimal() +
  labs(
    title = "Species–Area Curves for EMF Guild",
    x = "Number of Samples",
    y = "Accumulated Species Richness"
  ) +
  theme(
    legend.title = element_blank(),
    plot.title = element_text(face = "bold")
  )

#######################################################################

#POOLING
#extract the separate samples B1,2,3

process_sample_group <- function(pooled_col, single_cols, name) {
  # Get pooled and single sample data
  pooled_df <- allfungi[, c("GENUS", "Species", pooled_col)]
  single_df <- allfungi[, c("GENUS", "Species", single_cols)]
  
  # Combine genus and species
  pooled_df$species <- paste(pooled_df$GENUS, pooled_df$Species, sep = "_")
  single_df$species <- paste(single_df$GENUS, single_df$Species, sep = "_")
  
  # Presence/absence for pooled
  pooled_df$pres <- ifelse(pooled_df[[pooled_col]] > 0, 1, 0)
  
  # Presence/absence for singles
  single_df[single_cols] <- lapply(single_df[single_cols], function(x) ifelse(x > 0, 1, 0))
  
  # SAC for single samples
  sac <- specaccum(t(single_df[single_cols]), method = "random")
  
  # Tidy SAC dataframe
  sac_df <- data.frame(
    Samples = sac$sites,
    Richness = sac$richness,
    SD = sac$sd,
    Group = name
  )
  
  # Unique species in singles
  single_sp_df <- cbind(single_df$species, single_df[single_cols])
  single_sp_df <- as.data.frame(single_sp_df)
  colnames(single_sp_df)[1] <- "species"
  single_sp_df[, -1] <- lapply(single_sp_df[, -1], as.numeric)
  single_filtered <- single_sp_df[!apply(single_sp_df[, -1] == 0, 1, all), ]
  singles_list <- single_filtered$species
  
  # Unique species in pooled
  pooled_list <- pooled_df %>% filter(pres == 1) %>% pull(species)
  
  return(list(
    sac_df = sac_df,
    pooled = pooled_list,
    singles = singles_list
  ))
}

#----------------------------
# Define your groups here
#----------------------------

groups <- list(
  B1 = list(
    pooled_col = "B1",
    single_cols = c("A2", "A3", "A4", "A10","A11","A12","A18","A19","A20")
  ),
  B2 = list(
    pooled_col = "B2",
    single_cols = c("A39", "A40", "A33", "A31","A32","A25","A23","A24","A17")
  ),
  B3 = list(
    pooled_col = "B3",
    single_cols = c("A63", "A62", "A57", "A55","A56","A49","A47","A48","A41")
  )
)

#----------------------------
# Process each group
#----------------------------

sac_all <- list()
venn_lists <- list()

for (g in names(groups)) {
  result <- process_sample_group(
    pooled_col = groups[[g]]$pooled_col,
    single_cols = groups[[g]]$single_cols,
    name = g
  )
  
  sac_all[[g]] <- result$sac_df
  venn_lists[[g]] <- list(Pooled = result$pooled, Singles = result$singles)
}

#----------------------------
# Combine all SACs and plot
#----------------------------

sac_df_combined <- bind_rows(sac_all)

abline_data <- lapply(venn_lists, function(x) length(x$Pooled))
abline_df <- data.frame(Group = names(abline_data), Richness = unlist(abline_data))

# Plot with ablines
ggplot(sac_df_combined, aes(x = Samples, y = Richness, color = Group, fill = Group)) +
  geom_line(size = 1.2) +
  geom_ribbon(aes(ymin = Richness - SD, ymax = Richness + SD), alpha = 0.2, linetype = 0) +
  geom_hline(data = abline_df, aes(yintercept = Richness, color = Group), linetype = "dashed", size = 1) +
  theme_minimal() +
  labs(
    title = "Species-Area Curves for Pooled/unpooled",
    x = "Number of Samples",
    y = "Cumulative Species Richness"
  ) +
  theme(
    legend.title = element_blank(),
    plot.title = element_text(face = "bold")
  ) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = max(sac_df_combined$Samples)))

#----------------------------
# Draw Venn diagrams
#----------------------------

for (g in names(venn_lists)) {
  venn.plot <- venn.diagram(
    x = venn_lists[[g]],
    filename = NULL,
    fill = c("skyblue", "lightgreen"),
    alpha = 0.5,
    cex = 2,
    cat.cex = 1.5,
    cat.pos = 0,
    cat.dist = 0.05,
    main = paste("Species Overlap: Pooled vs Singles,", g)
  )
  grid.newpage()
  grid.draw(venn.plot)
}

library(gridExtra)
library(grid)

# Create and store Venn diagram grobs as proper grobs
venn_grobs <- lapply(names(venn_lists), function(g) {
  venn <- venn.diagram(
    x = venn_lists[[g]],
    filename = NULL,
    fill = c("skyblue", "lightgreen"),
    alpha = 0.5,
    cex = 2,
    cat.cex = 1.5,
    cat.pos = 0,
    cat.dist = 0.05,
    main = paste("Species Overlap: Pooled vs Singles,", g)
  )
  grobTree(venn)  # <— wrap in grobTree to make it compatible
})

# Plot them in a grid
grid.newpage()
grid.arrange(grobs = venn_grobs, ncol = 3)
################################################################################

###########How many species do we generally find in a sample, is a rhizo sample
#as good/better than a soil, or root etc

#first - what is mean richness of a single sample - an A sample
single_samples = allfungi[,c(3:7,41:99)]
single_samples_pa = single_samples
single_samples_pa = as.data.frame(lapply(single_samples_pa, function(x) ifelse(x>0,1,0)))
single_sample_richness = colSums(single_samples_pa)
single_sample_lable = rep('single',64)
single_samples_df = cbind.data.frame(single_sample_lable, single_sample_richness)
colnames(single_samples_df) = c('group','richness')

#now to pooled, B1,B2,B3 
pooled_samples = allfungi[,c(14,17,20)]
pooled_samples_pa = pooled_samples
pooled_samples_pa = as.data.frame(lapply(pooled_samples_pa, function(x) ifelse(x>0,1,0)))
pooled_sample_richness = colSums((pooled_samples_pa))
pooled_sample_lable = rep('pooled',3)
pooled_samples_df = cbind.data.frame(pooled_sample_lable, pooled_sample_richness)
colnames(pooled_samples_df) = c('group','richness')

#the roots
roots = allfungi[,c(32:40)]
roots_pa = roots
roots_pa = as.data.frame(lapply(roots_pa, function(x) ifelse(x>0,1,0)))
roots_sample_lable = rep('root',9)
roots_sample_richness = colSums(roots_pa)
roots_sample_label = rep('roots',9)
roots_df = cbind.data.frame(roots_sample_label, roots_sample_richness)
colnames(roots_df) = c('group','richness')

#the rhizo soil
rhizo = allfungi[,c(23:31)]
rhizo_pa = rhizo
rhizo_pa = as.data.frame(lapply(rhizo_pa, function(x) ifelse(x>0,1,0)))
rhizo_sample_richness = colSums(rhizo_pa)
rhizo_sample_lable = rep('rhizo',9)
rhizo_df = cbind.data.frame(rhizo_sample_lable, rhizo_sample_richness)
colnames(rhizo_df) = c('group','richness')

df = rbind.data.frame(single_samples_df, pooled_samples_df, roots_df, rhizo_df)

ggplot(df, aes(x = group, y = richness)) +
  geom_boxplot(fill = "lightblue", color = "black") +
  theme_minimal() +
  labs(title = "Species Richness by Group",
       x = "Group",
       y = "Species Richness")

################################################################################

allfungi_pa <- allfungi
allfungi_pa[, -c(1:2, 100:124)] <- lapply(allfungi_pa[, -c(1:2, 100:124)], function(x) ifelse(x > 0, 1, 0))

# Step 2: Calculate species richness per sample (sum of 1s in each column)
sample_richness <- colSums(allfungi_pa[,-c(1:2, 100:124)], na.rm = TRUE)

# Step 3: Plot the distribution of species richness across samples
boxplot(sample_richness,
        main = "Distribution of Species Richness per Sample",
        ylab = "Number of Species",
        col = "lightblue")
sample_richness = colSums(allfungi[c(3:99)])
boxplot(sample_richness,
        main = "Distribution of Species Richness per Sample",
        ylab = "Number of Species",
        col = "lightblue")

#which samples tend to be the richest? Any patterns

sample_data <- allfungi_pa[, -c(1:2, 100:124)]

# Calculate species richness (sum of 1s) per sample
richness <- colSums(sample_data)

# Convert to data frame for plotting
richness_df <- data.frame(
  Sample = names(richness),
  Richness = as.numeric(richness)
)

# Order by richness descending
richness_df <- richness_df[order(-richness_df$Richness), ]

# Plot using ggplot2
library(ggplot2)
ggplot(richness_df, aes(x = reorder(Sample, -Richness), y = Richness)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_minimal() +
  labs(title = "Species Richness per Sample",
       x = "Sample",
       y = "Species Richness") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

################################################################################

#now compare the repeated extracts from a single sample and a pooled sample.
#Is it better to take three separate samples, or do three extracts from the same sample
#What is richness of three Extracts compared to three separate, and how does community overlap

#for a12, collect a12 and the reps
a12 = cbind.data.frame(allfungi$A12, allfungi$A121, allfungi$A122)
a12[a12>0] = 1

#ust plot as points rather than SAC, coz only 3 items
species_a12 <- which(a12$A12 == 1)

# Species in a122 not in a12
species_a121_new <- which(a12$A121 == 1 & a12$A12== 0)

# Species in a123 not in a12 or a122
species_a123_new <- which(a12$A122 == 1 & a12$A12 == 0 & a12$A121 == 0)

count1 <- length(species_a12)
count2 <- count1 + length(species_a121_new)
count3 <- count2 + length(species_a123_new)

repeats = c(count1,count2,count3)

#compare this to taking three separate samples
#look at different combinations of A samples in the area of A12
#A12+A3+A4
#A12+A13+A20
#A12+A21+A5

three.1 = cbind.data.frame(allfungi$A12,allfungi$A3,allfungi$A4)
three.2 = cbind.data.frame(allfungi$A12,allfungi$A13,allfungi$A20)
three.3 = cbind.data.frame(allfungi$A12,allfungi$A21,allfungi$A5)

three.1[three.1 > 0] = 1
three.2[three.2 > 0] = 1
three.3[three.3 > 0] = 1

species_three.1 <- which(three.1[,1] == 1)
three.1_new <- which(three.1[,2] == 0 & three.1[,1] == 1)
three.1_newagain = which(three.1[,1] == 0 & three.1[,2] == 0 & three.1[,3] == 1)

count1 <- length(species_three.1)
count2 <- count1 + length(three.1_new)
count3 <- count2 + length(three.1_newagain)

#add these to the plot_df
singles.1 = c(count1,count2,count3)
##########################################
#create the #SAC for the next set of 3 singles, A12,13,20
species_three.2 <- which(three.2[,1] == 1)
three.2_new <- which(three.2[,2] == 0 & three.2[,1] == 1)
three.2_newagain = which(three.2[,1] == 0 & three.2[,2] == 0 & three.2[,3] == 1)

count1 <- length(species_three.2)
count2 <- count1 + length(three.2_new)
count3 <- count2 + length(three.2_newagain)

#add these to the plot_df
singles.2 = c(count1,count2,count3)

########################################

#create the #SAC for the next set of 3 singles, A12,21,5
species_three.3 <- which(three.3[,1] == 1)
three.3_new <- which(three.3[,2] == 0 & three.3[,1] == 1)
three.3_newagain = which(three.3[,1] == 0 & three.3[,2] == 0 & three.3[,3] == 1)

count1 <- length(species_three.3)
count2 <- count1 + length(three.3_new)
count3 <- count2 + length(three.3_newagain)

#add these to the plot_df
singles.3 = c(count1,count2,count3)

# Create data frame for plotting
plot_df <- data.frame(
  x = c(1,2,3),
  repeats = repeats,
  singles1 = singles.1,
  singles2 = singles.2,
  singles3 = singles.3
)

library(tidyr)
df_long <- pivot_longer(plot_df, 
                        cols = 2:5, 
                        names_to = "Variable", 
                        values_to = "Value")

ggplot(df_long, aes(x = x, y = Value, group = Variable, color = Variable)) +
  geom_line() +
  geom_point(size = 3) +
  labs(title = "Cumulative Species Richness Across Samples, A12",
       y = "Cumulative Number of Species",
       x = "Sample") +
  theme_minimal()

